services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    working_dir: /backend

  backend:
    build: ./backend
    image: rails-backend
    command: bash -c "bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    working_dir: /backend
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password

  front:
    build: ./front
    image: react-front
    command: sh -c "npm install && npm run start"
    ports:
      - "4000:4000"
    working_dir: /front
    volumes:
      - ./front:/front
